### ISSUE TITLE
Add support for Ukrainian

### ISSUE THREAD

**Issue by andrenatal** [mozilla-l10n/firefox-translations-l10n#14]
@flodolo We've just landed support for Ukrainian https://github.com/mozilla/firefox-translations/commit/7dfb0260abc497d1bc964f284605e73109f825aa. Can we also add Ukrainian here in order to be localized? 

Thanks

**Comment by flodolo** [comment]
A couple of notes:
* We don't add locales here, we add them through Pontoon.
* We normally don't add new locales, locales can ask to be added to projects.

With that said, I'll add Ukrainian, but we should find a better way to do it for the future (and accept that new locales might not be supported in the UI, while they are supported by the engine).
